version: "3"
services:
  server:
    container_name: orbit-net-server
    working_dir: /app
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: orbit-net-mongo
    ports:
      - 27017
    volumes:
      - ./data/mongo/data:/data/db
