version: "3"
services:
  nginx:
    build:
      context: docker/nginx
    image: orbit-net-nginx
    container_name: orbit-net-nginx
    restart: always
    depends_on:
      - server
      - front
    ports:
      - "80:80"
      - "443:443"

  server:
    build:
      context: .
    image: orbit-net-server
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 8080

  front:
    build:
      context: ./react-ui
    image: orbit-net-front
    container_name: orbit-net-front
    working_dir: /app
    restart: always
    environment:
      - NODE_ENV=production
    ports:
      - 3000
